# Generated by Django 2.2.16 on 2020-09-29 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='ws',
            field=models.OneToOneField(blank=True, default='ws', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customtext_ws', to='home.CustomText'),
        ),
    ]
